"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[line_break]
disabled = true


[character]
disabled = true

[package]
disabled = true

[git_branch]
style = "italic white"
format = '[$symbol$branch]($style) '

[git_metrics]
disabled = false

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
disabled = true

[directory]
truncation_length = 1


[battery]
discharging_symbol = "⚡️"
[[battery.display]]
threshold = 10
style = "bold red"

[python]
disabled = true

[lua]
disabled = true

[java]
disabled = true

[golang]
disabled = true

[cmd_duration]
disabled = true
