# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[line_break]
disabled = true

[character]
disabled = true

[package]
disabled = true

[directory]
truncation_length = 100
truncate_to_repo = true
style = "white"
format = "[ $path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = " "
style = "italic white"
format = '[$symbol$branch]($style) '

[git_metrics]
disabled = false

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
disabled = true

[java]
disabled = true

[python]
disabled = true

[rust]
disabled = true

[golang]
disabled = true

[c]
disabled = true

[cmd_duration]
disabled = true
