# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[line_break]
disabled = true


[character]
disabled = true

[package]
disabled = true

[git_branch]
symbol = " "
style = "italic white"
format = '[$symbol$branch]($style) '

[git_metrics]
disabled = false

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
disabled = true

[directory]
truncation_length = 3
truncation_symbol = "…/"


[battery]
discharging_symbol = "⚡️"
[[battery.display]]
threshold = 10
style = "bold red"

[python]
disabled = true
